/* =========================================================
   data.js
   Sample seed data for JobNest.
   `SEED_JOBS` and `COMPANIES` are copied into LocalStorage
   on first load (see storage.js -> Store.init()).
   ========================================================= */

/* Brand colours used for the company logo avatars.
   Each company maps to a gradient so logos look distinct. */
const COMPANY_COLORS = {
  Google: "#4285F4",
  Microsoft: "#0078D4",
  Amazon: "#FF9900",
  TCS: "#004b8d",
  Infosys: "#007cc3",
  Wipro: "#341e6e",
  Accenture: "#a100ff",
  Deloitte: "#86BC25",
  "Tech Mahindra": "#e21e26",
  TechNova: "#4f46e5",
  DataForge: "#0ea5e9",
  CloudPeak: "#059669",
  Finlytics: "#db2777",
  PixelCraft: "#f97316",
  ByteWorks: "#7c3aed",
};

/* Companies shown on the Companies page. openJobs is computed
   dynamically from the job list, but we keep an industry/location. */
const COMPANIES = [
  { name: "Google", industry: "Internet & Technology", location: "Hyderabad" },
  { name: "Microsoft", industry: "Software & Cloud", location: "Bangalore" },
  { name: "Amazon", industry: "E-commerce & Cloud", location: "Chennai" },
  { name: "TCS", industry: "IT Services & Consulting", location: "Mumbai" },
  { name: "Infosys", industry: "IT Services & Consulting", location: "Pune" },
  { name: "Wipro", industry: "IT Services", location: "Bangalore" },
  { name: "Accenture", industry: "Consulting & Technology", location: "Delhi" },
  { name: "Deloitte", industry: "Consulting & Audit", location: "Hyderabad" },
  { name: "Tech Mahindra", industry: "IT & Networking", location: "Pune" },
  { name: "TechNova", industry: "Product Startup", location: "Remote" },
];

/* Helper to build responsibilities / requirements / benefits
   so we don't repeat huge blocks for every job. */
function jobExtras() {
  return {
    responsibilities: [
      "Design, build and maintain efficient, reusable and reliable code.",
      "Collaborate with cross-functional teams to define and ship new features.",
      "Identify bottlenecks and bugs, and devise solutions to these problems.",
      "Participate in code reviews and uphold engineering best practices.",
    ],
    requirements: [
      "Strong problem-solving skills and attention to detail.",
      "Good understanding of data structures and algorithms.",
      "Ability to write clean, well-documented and testable code.",
      "Excellent communication and teamwork abilities.",
    ],
    benefits: [
      "Competitive salary with annual performance bonus.",
      "Comprehensive health insurance for you and your family.",
      "Flexible work hours and generous paid leave.",
      "Learning budget and certification reimbursements.",
    ],
  };
}

/* 30+ realistic jobs across cities, skills, experience and salary. */
const SEED_JOBS = [
  {
    id: 1,
    title: "Software Engineer",
    company: "Google",
    location: "Hyderabad",
    experience: "3-5 Years",
    salary: "₹24-38 LPA",
    salaryMin: 24,
    type: "Full Time",
    mode: "Hybrid",
    skills: ["Java", "Python", "SQL", "System Design"],
    posted: "2 days ago",
    postedDays: 2,
    description:
      "Join our core platform team to build large-scale distributed systems that serve billions of users worldwide.",
    ...jobExtras(),
  },
  {
    id: 2,
    title: "Frontend Developer",
    company: "TechNova",
    location: "Hyderabad",
    experience: "0-2 Years",
    salary: "₹5-8 LPA",
    salaryMin: 5,
    type: "Full Time",
    mode: "Remote",
    skills: ["HTML", "CSS", "JavaScript", "React"],
    posted: "1 day ago",
    postedDays: 1,
    description:
      "Craft delightful, accessible user interfaces for our SaaS product used by thousands of teams every day.",
    ...jobExtras(),
  },
  {
    id: 3,
    title: "Backend Developer",
    company: "Amazon",
    location: "Bangalore",
    experience: "2-5 Years",
    salary: "₹18-28 LPA",
    salaryMin: 18,
    type: "Full Time",
    mode: "On-site",
    skills: ["Java", "Node.js", "SQL", "AWS"],
    posted: "3 days ago",
    postedDays: 3,
    description:
      "Build resilient, high-throughput backend services powering our e-commerce checkout experience.",
    ...jobExtras(),
  },
  {
    id: 4,
    title: "Full Stack Developer",
    company: "Infosys",
    location: "Pune",
    experience: "3-5 Years",
    salary: "₹12-18 LPA",
    salaryMin: 12,
    type: "Full Time",
    mode: "Hybrid",
    skills: ["React", "Node.js", "MongoDB", "JavaScript"],
    posted: "5 days ago",
    postedDays: 5,
    description:
      "Own features end-to-end across the stack, from database schema to polished React front-ends.",
    ...jobExtras(),
  },
  {
    id: 5,
    title: "Java Developer",
    company: "TCS",
    location: "Mumbai",
    experience: "2-5 Years",
    salary: "₹8-14 LPA",
    salaryMin: 8,
    type: "Full Time",
    mode: "On-site",
    skills: ["Java", "Spring Boot", "SQL", "Microservices"],
    posted: "4 days ago",
    postedDays: 4,
    description:
      "Develop enterprise-grade Java applications for global banking and finance clients.",
    ...jobExtras(),
  },
  {
    id: 6,
    title: "Python Developer",
    company: "DataForge",
    location: "Remote",
    experience: "1-3 Years",
    salary: "₹9-15 LPA",
    salaryMin: 9,
    type: "Full Time",
    mode: "Remote",
    skills: ["Python", "Django", "SQL", "REST API"],
    posted: "2 days ago",
    postedDays: 2,
    description:
      "Build data-heavy APIs and automation pipelines using Python and modern tooling.",
    ...jobExtras(),
  },
  {
    id: 7,
    title: "React Developer",
    company: "PixelCraft",
    location: "Bangalore",
    experience: "0-2 Years",
    salary: "₹6-10 LPA",
    salaryMin: 6,
    type: "Full Time",
    mode: "Hybrid",
    skills: ["React", "JavaScript", "CSS", "Redux"],
    posted: "6 days ago",
    postedDays: 6,
    description:
      "Turn design systems into pixel-perfect, performant React components and interfaces.",
    ...jobExtras(),
  },
  {
    id: 8,
    title: "Data Analyst",
    company: "Finlytics",
    location: "Chennai",
    experience: "1-3 Years",
    salary: "₹7-12 LPA",
    salaryMin: 7,
    type: "Full Time",
    mode: "On-site",
    skills: ["SQL", "Python", "Excel", "Power BI"],
    posted: "1 day ago",
    postedDays: 1,
    description:
      "Transform raw data into actionable insights and dashboards for business stakeholders.",
    ...jobExtras(),
  },
  {
    id: 9,
    title: "Software Tester",
    company: "Wipro",
    location: "Bangalore",
    experience: "0-2 Years",
    salary: "₹4-7 LPA",
    salaryMin: 4,
    type: "Full Time",
    mode: "On-site",
    skills: ["Selenium", "Java", "Manual Testing", "SQL"],
    posted: "7 days ago",
    postedDays: 7,
    description:
      "Ensure product quality through comprehensive manual and automated testing.",
    ...jobExtras(),
  },
  {
    id: 10,
    title: "DevOps Engineer",
    company: "CloudPeak",
    location: "Remote",
    experience: "3-5 Years",
    salary: "₹16-26 LPA",
    salaryMin: 16,
    type: "Full Time",
    mode: "Remote",
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    posted: "3 days ago",
    postedDays: 3,
    description:
      "Automate infrastructure and deployment pipelines for cloud-native applications.",
    ...jobExtras(),
  },
  {
    id: 11,
    title: "UI/UX Designer",
    company: "PixelCraft",
    location: "Pune",
    experience: "2-5 Years",
    salary: "₹8-14 LPA",
    salaryMin: 8,
    type: "Full Time",
    mode: "Hybrid",
    skills: ["Figma", "Prototyping", "User Research", "CSS"],
    posted: "2 days ago",
    postedDays: 2,
    description:
      "Design intuitive product experiences backed by research and a robust design system.",
    ...jobExtras(),
  },
  {
    id: 12,
    title: "Full Stack Java Developer",
    company: "Accenture",
    location: "Delhi",
    experience: "3-5 Years",
    salary: "₹13-20 LPA",
    salaryMin: 13,
    type: "Full Time",
    mode: "Hybrid",
    skills: ["Java", "Spring Boot", "React", "SQL"],
    posted: "4 days ago",
    postedDays: 4,
    description:
      "Deliver full-stack enterprise solutions with Java on the backend and React on the front-end.",
    ...jobExtras(),
  },
  {
    id: 13,
    title: "Senior Software Engineer",
    company: "Microsoft",
    location: "Bangalore",
    experience: "5+ Years",
    salary: "₹35-55 LPA",
    salaryMin: 35,
    type: "Full Time",
    mode: "Hybrid",
    skills: ["C#", ".NET", "Azure", "System Design"],
    posted: "1 day ago",
    postedDays: 1,
    description:
      "Lead the design and development of cloud services on the Azure platform.",
    ...jobExtras(),
  },
  {
    id: 14,
    title: "Node.js Developer",
    company: "ByteWorks",
    location: "Remote",
    experience: "1-3 Years",
    salary: "₹8-13 LPA",
    salaryMin: 8,
    type: "Full Time",
    mode: "Remote",
    skills: ["Node.js", "Express", "MongoDB", "JavaScript"],
    posted: "5 days ago",
    postedDays: 5,
    description:
      "Build scalable REST and GraphQL APIs for our high-traffic consumer apps.",
    ...jobExtras(),
  },
  {
    id: 15,
    title: "Machine Learning Engineer",
    company: "DataForge",
    location: "Hyderabad",
    experience: "3-5 Years",
    salary: "₹20-32 LPA",
    salaryMin: 20,
    type: "Full Time",
    mode: "On-site",
    skills: ["Python", "TensorFlow", "SQL", "Machine Learning"],
    posted: "2 days ago",
    postedDays: 2,
    description:
      "Design and ship ML models that power personalisation and recommendation systems.",
    ...jobExtras(),
  },
  {
    id: 16,
    title: "QA Automation Engineer",
    company: "Tech Mahindra",
    location: "Pune",
    experience: "2-5 Years",
    salary: "₹7-12 LPA",
    salaryMin: 7,
    type: "Full Time",
    mode: "On-site",
    skills: ["Selenium", "Java", "TestNG", "CI/CD"],
    posted: "6 days ago",
    postedDays: 6,
    description:
      "Own the automation framework and improve release quality across teams.",
    ...jobExtras(),
  },
  {
    id: 17,
    title: "Cloud Architect",
    company: "Deloitte",
    location: "Hyderabad",
    experience: "5+ Years",
    salary: "₹30-48 LPA",
    salaryMin: 30,
    type: "Full Time",
    mode: "Hybrid",
    skills: ["AWS", "Azure", "Kubernetes", "System Design"],
    posted: "3 days ago",
    postedDays: 3,
    description:
      "Architect secure, scalable cloud solutions for large enterprise clients.",
    ...jobExtras(),
  },
  {
    id: 18,
    title: "Frontend Engineer (Intern)",
    company: "TechNova",
    location: "Remote",
    experience: "Fresher",
    salary: "₹0-3 LPA",
    salaryMin: 0,
    type: "Internship",
    mode: "Remote",
    skills: ["HTML", "CSS", "JavaScript", "React"],
    posted: "1 day ago",
    postedDays: 1,
    description:
      "A 6-month internship to learn and build production React interfaces with mentorship.",
    ...jobExtras(),
  },
  {
    id: 19,
    title: "Business Analyst",
    company: "Accenture",
    location: "Mumbai",
    experience: "1-3 Years",
    salary: "₹6-11 LPA",
    salaryMin: 6,
    type: "Full Time",
    mode: "On-site",
    skills: ["SQL", "Excel", "Power BI", "Communication"],
    posted: "4 days ago",
    postedDays: 4,
    description:
      "Bridge business needs and technology teams by translating requirements into solutions.",
    ...jobExtras(),
  },
  {
    id: 20,
    title: "Android Developer",
    company: "ByteWorks",
    location: "Bangalore",
    experience: "2-5 Years",
    salary: "₹10-16 LPA",
    salaryMin: 10,
    type: "Full Time",
    mode: "Hybrid",
    skills: ["Kotlin", "Java", "Android", "REST API"],
    posted: "5 days ago",
    postedDays: 5,
    description:
      "Develop and maintain feature-rich Android apps with millions of downloads.",
    ...jobExtras(),
  },
  {
    id: 21,
    title: "Data Scientist",
    company: "Finlytics",
    location: "Bangalore",
    experience: "3-5 Years",
    salary: "₹18-30 LPA",
    salaryMin: 18,
    type: "Full Time",
    mode: "Hybrid",
    skills: ["Python", "Machine Learning", "SQL", "Statistics"],
    posted: "2 days ago",
    postedDays: 2,
    description:
      "Build predictive models and experiments that drive product and business decisions.",
    ...jobExtras(),
  },
  {
    id: 22,
    title: "PHP Developer",
    company: "Wipro",
    location: "Chennai",
    experience: "1-3 Years",
    salary: "₹5-9 LPA",
    salaryMin: 5,
    type: "Full Time",
    mode: "On-site",
    skills: ["PHP", "Laravel", "MySQL", "JavaScript"],
    posted: "8 days ago",
    postedDays: 8,
    description:
      "Maintain and enhance web applications built on the Laravel framework.",
    ...jobExtras(),
  },
  {
    id: 23,
    title: "Product Manager",
    company: "Microsoft",
    location: "Hyderabad",
    experience: "5+ Years",
    salary: "₹28-45 LPA",
    salaryMin: 28,
    type: "Full Time",
    mode: "Hybrid",
    skills: ["Product Strategy", "Analytics", "Communication", "Agile"],
    posted: "1 day ago",
    postedDays: 1,
    description:
      "Define product vision and roadmap, and lead cross-functional teams to deliver value.",
    ...jobExtras(),
  },
  {
    id: 24,
    title: "Junior Data Analyst",
    company: "TCS",
    location: "Delhi",
    experience: "Fresher",
    salary: "₹3-5 LPA",
    salaryMin: 3,
    type: "Full Time",
    mode: "On-site",
    skills: ["SQL", "Excel", "Python", "Data Visualization"],
    posted: "3 days ago",
    postedDays: 3,
    description:
      "Entry-level role assisting analytics teams with reporting and data cleaning.",
    ...jobExtras(),
  },
  {
    id: 25,
    title: "Site Reliability Engineer",
    company: "Amazon",
    location: "Hyderabad",
    experience: "3-5 Years",
    salary: "₹22-36 LPA",
    salaryMin: 22,
    type: "Full Time",
    mode: "On-site",
    skills: ["AWS", "Docker", "Kubernetes", "Python"],
    posted: "4 days ago",
    postedDays: 4,
    description:
      "Keep our services reliable at scale through automation, monitoring and incident response.",
    ...jobExtras(),
  },
  {
    id: 26,
    title: "WordPress Developer",
    company: "PixelCraft",
    location: "Remote",
    experience: "0-2 Years",
    salary: "₹3-6 LPA",
    salaryMin: 3,
    type: "Contract",
    mode: "Remote",
    skills: ["PHP", "WordPress", "CSS", "JavaScript"],
    posted: "6 days ago",
    postedDays: 6,
    description:
      "Build and customise WordPress themes and plugins for client websites.",
    ...jobExtras(),
  },
  {
    id: 27,
    title: "Angular Developer",
    company: "Infosys",
    location: "Pune",
    experience: "2-5 Years",
    salary: "₹9-15 LPA",
    salaryMin: 9,
    type: "Full Time",
    mode: "Hybrid",
    skills: ["Angular", "TypeScript", "RxJS", "CSS"],
    posted: "5 days ago",
    postedDays: 5,
    description:
      "Develop enterprise single-page applications using Angular and TypeScript.",
    ...jobExtras(),
  },
  {
    id: 28,
    title: "Database Administrator",
    company: "Deloitte",
    location: "Mumbai",
    experience: "3-5 Years",
    salary: "₹12-20 LPA",
    salaryMin: 12,
    type: "Full Time",
    mode: "On-site",
    skills: ["SQL", "PostgreSQL", "Oracle", "Performance Tuning"],
    posted: "7 days ago",
    postedDays: 7,
    description:
      "Manage, secure and optimise mission-critical database systems.",
    ...jobExtras(),
  },
  {
    id: 29,
    title: "Marketing Intern",
    company: "TechNova",
    location: "Bangalore",
    experience: "Fresher",
    salary: "₹0-3 LPA",
    salaryMin: 0,
    type: "Internship",
    mode: "On-site",
    skills: ["SEO", "Content Writing", "Social Media", "Analytics"],
    posted: "2 days ago",
    postedDays: 2,
    description:
      "Support digital marketing campaigns and learn growth fundamentals hands-on.",
    ...jobExtras(),
  },
  {
    id: 30,
    title: "Backend Developer (Python)",
    company: "CloudPeak",
    location: "Chennai",
    experience: "1-3 Years",
    salary: "₹8-14 LPA",
    salaryMin: 8,
    type: "Full Time",
    mode: "Remote",
    skills: ["Python", "FastAPI", "SQL", "Docker"],
    posted: "3 days ago",
    postedDays: 3,
    description:
      "Design robust backend services and APIs for our cloud analytics platform.",
    ...jobExtras(),
  },
  {
    id: 31,
    title: "Part Time Web Developer",
    company: "ByteWorks",
    location: "Remote",
    experience: "0-2 Years",
    salary: "₹3-6 LPA",
    salaryMin: 3,
    type: "Part Time",
    mode: "Remote",
    skills: ["HTML", "CSS", "JavaScript", "React"],
    posted: "1 day ago",
    postedDays: 1,
    description:
      "Flexible part-time role building and maintaining marketing websites.",
    ...jobExtras(),
  },
  {
    id: 32,
    title: "Salesforce Developer",
    company: "Tech Mahindra",
    location: "Delhi",
    experience: "2-5 Years",
    salary: "₹10-18 LPA",
    salaryMin: 10,
    type: "Full Time",
    mode: "Hybrid",
    skills: ["Salesforce", "Apex", "JavaScript", "SQL"],
    posted: "4 days ago",
    postedDays: 4,
    description:
      "Customise and extend Salesforce CRM to meet complex enterprise workflows.",
    ...jobExtras(),
  },
];
